name: Development Build
on: push

env:
  APP_VERSION: "1.1.1"
  MC: "1.21.5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Build
        run: ./gradlew build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: dist/
        
